# 配置数据源，这里目前是运行在IP地址为8.130.12.168的云服务器上的数据库
spring:
  datasource:
    url: jdbc:mysql://8.130.12.168:3306/hetadb?useUnicode=yes&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 735568
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#  # Jackson 配置
#    jackson:
#      date-format: yyyy-MM-dd HH:mm:ss  # 指定日期格式
#      time-zone: GMT+8                  # 指定时区

# 配置Mybatis映射
mybatis:
  mapper-locations: classpath:/Mapper/*.xml
  type-aliases-package: com.heta.entity

# 配置阿里云OSS上传需要的密钥等
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tSN6c3PccwyohJCAo9j
    accessKeySecret: GIkDt8md0LZZNjLFHtyFsa7AtaSlla
    bucketName: heta-images

server:
  address: 0.0.0.0
  port: 8080